---
# the default expected insertions to filter. If no value provided on creating filter, this value will be used
defaultExpectedInsertions: 1000000

# the default desired false positive probability for a filter. If no value provided on creating filter, this value will be used
defaultFalsePositiveProbability: 0.01

# the default valid seconds after create for a filter. If no value provided on creating filter, this value will be used
defaultValidSecondsAfterCreate: 86400

# maximum allowed http/https concurrent connections
maxHttpConnections: 1000

# maximum allowed length of the content decoded at the session layer. the default value is 10 MB
maxHttpRequestLength: 10485760

# the default timeout of a request
requestTimeoutSeconds: 5

# the idle timeout of a connection in milliseconds for keep-alive
idleTimeoutMillis: 10000

# maximum thread pool size to execute internal potential long running tasks
maxWorkerThreadPoolSize: 10

# the configuration options for every underlying TCP socket
channelOptions:
  SO_BACKLOG: 2048
  SO_RCVBUF: 2048
  SO_SNDBUF: 2048
  TCP_NODELAY: true

# the interval for the purge thread to scan all the filters to find and clean expired filters
purgeFilterIntervalMillis: 300

# config when to save all the filters on disk. Will save the filters if both the given number of seconds and the given
# number of update operations against the service occurred.
# In the example below the behaviour will be to save:
# after 900 sec if at least 1 filter update operation occurred
# after 300 sec if at least 100 filter update operation occurred
# after 60 sec if at least 10000 filter update operation occurred
triggerPersistenceCriteria:
  - periodInSeconds: 900
    updatesMoreThan: 1
  - periodInSeconds: 300
    updatesMoreThan: 100
  - periodInSeconds: 60
    updatesMoreThan: 10000

# the path to a directory to store persistent file. Leave it empty to use the path to "user.dir" system property
persistentStorageDirectory: ~

# 100KB
channelBufferSizeForFilterPersistence: 102400

# when this switch is on, we try to recover filters from a corrupted or unfinished persistent file as many filters as we can;
# otherwise, we will throw an exception when we make sure that the persistent file is corrupted or unfinished.
allowRecoverFromCorruptedPersistentFile: true

# the number of milliseconds to wait for active requests to go end before shutting down. 0 means the server
# will stop right away without waiting
gracefulShutdownQuietPeriodMillis: 0

# the number of milliseconds to wait before shutting down the server regardless of active requests.
# This should be set to a time greater than gracefulShutdownQuietPeriodMillis to ensure the server
# shuts down even if there is a stuck request.
gracefulShutdownTimeoutMillis: 0
