---
# the interval for the purge thread to scan all the filters to find and clean expired filters
purgeFilterIntervalMillis: 300
# maximum allowed http/https concurrent connections
maxHttpConnections: 1000
# maximum allowed length of the content decoded at the session layer. the default value is 10 MB
maxHttpRequestLength: 10485760
# the default timeout of a request
defaultRequestTimeoutSeconds: 5
# the default expected insertions to filter. If no value provided on creating filter, this value will be used
defaultExpectedInsertions: 1000000
# the default desired false positive probability for a filter. If no value provided on creating filter, this value will be used
defaultFalsePositiveProbability: 0.0001
# the default valid seconds after create for a filter. If no value provided on creating filter, this value will be used
defaultValidSecondsAfterCreate: 86400
# the configuration options for every underlying TCP socket
channelOptions:
  SO_BACKLOG: 2048
  SO_RCVBUF: 2048
  SO_SNDBUF: 2048
  TCP_NODELAY: True